### ISSUE TITLE
PyPI GitHub Action is broken

### ISSUE THREAD

**Issue by jtyoung84** [AllenNeuralDynamics/aind-data-transfer#100]
**Describe the bug**
The latest version is broken. We can fix it by changing the line in the `tag.yml` from `uses: pypa/gh-action-pypi-publish@release/v1` to `uses: pypa/gh-action-pypi-publish@release/v1.5`

**Additional context**

**Comment by aricAI** [comment]
Fix is blocked by unrelated error
