### ISSUE TITLE
`spikeinterface` is required for imaging transcode job

### ISSUE THREAD

**Issue by carshadi** [AllenNeuralDynamics/aind-data-transfer#142]
When running a spim transcode job

```shell
Traceback (most recent call last):
  File "/home/cameron.arshadi/repos/aind-data-transfer/src/aind_data_transfer/jobs/transcode_job.py", line 14, in <module>
    from aind_data_transfer.readers import ImagingReaders
  File "/allen/programs/aind/workgroups/msma/cameron.arshadi/miniconda3/envs/aind-data-transfer/lib/python3.10/site-packages/aind_data_transfer/readers.py", line 10, in <module>
    import spikeinterface.extractors as se
ModuleNotFoundError: No module named 'spikeinterface'
```

**To Reproduce**
install the imaging dependencies only
```shell
pip install -e .[imaging]
./post_install.sh
```

then run the transcode job
```./scripts/bin/transcode_job.sh```

A couple potential fixes could be to include `spikeinterface` in the imaging dependencies, or refactor the `readers.py` module into `ephys_readers` and `spim_readers` or similar

**Comment by alejoe91** [comment]
@carshadi we could also make the imports lazy, so that if a package is not required for a use case (like spikeinterface for reading imaging data) it's not imported. If you're ok with I'll make a PR

**Comment by carshadi** [comment]
@alejoe91 that sounds good to me!
