### ISSUE TITLE
Fetch `subject.json` using `aind-metadata-service` during exaSPIM data upload

### ISSUE THREAD

**Issue by dyf** [AllenNeuralDynamics/aind-data-transfer#169]

**Comment by camilolaiton** [comment]
Please, check [this](https://github.com/AllenNeuralDynamics/aind-data-transfer/blob/main/src/aind_data_transfer/writers/imaging_writers.py#L319) where I get the subject data from the `aind-metadata-service` for the SmartSPIM datasets.
