### ISSUE TITLE
Let `submit.py` accept a json config file for input args

### ISSUE THREAD

**Issue by carshadi** [AllenNeuralDynamics/aind-data-transfer#174]
# User story
`scripts/cluster/submit.py` currently requires typing out the arguments manually. We should add support for parsing a single json config file with all the parameters (either using `argschema` or something else)

# Acceptance criteria
- [ ] This is something that can be verified to show that this user story is satisfied.

# Sprint Ready Checklist 
- [ ] 1. Acceptance criteria defined
- [ ] 2. Team understands acceptance criteria
- [ ] 3. Team has defined solution / steps to satisfy acceptance criteria
- [ ] 4. Acceptance criteria is verifiable / testable
- [ ] 5. External / 3rd Party dependencies identified
- [ ] 6. Ticket is prioritized and sized

# Notes
*Add any helpful notes here.*

**Comment by mekhlakapoor** [comment]
no longer an issue
