### ISSUE TITLE
Write ingest script for MRI sessions

### ISSUE THREAD

**Issue by dyf** [AllenNeuralDynamics/aind-data-transfer#237]
Work with Yoni and Galen to create script to ingest MRI acquisition metadata from Bruker machine and generate `acquisition.json`.

Notes:
- An overview of the Bruker file format: https://imaging.mrc-cbu.cam.ac.uk/imaging/FormatBruker
- David's (mis)adventure parsing subject metadata: https://github.com/AllenNeuralDynamics/ephys-migration-scripts/blob/5a7ba8074726ae85f01e9fe3f6bde9245dea9d05/mri.py#L167

**Comment by saskiad** [comment]
this requires the MRI schema to be updated first

**Comment by Sun-flow** [comment]
@saskiad should reach out to Galen to find out if they have started doing any of this one their own

**Comment by saskiad** [comment]
- [ ] `scan_sequence_type` comes from `method` ##$Method=RARE
- [ ] `echo_time` comes from `method` ##$PVM_EchoTime=5.33333333333333
- [ ] `effective_echo_time` comes from `method` ##$EffectiveTE=( 1 )
10.6666666666667
- [ ] `rare_factor` comes from `method` ##$PVM_RareFactor=4
- [ ] `repetition_time` comes from `method` ##$PVM_RepetitionTime=500
- [ ] `vc_orientation` comes from `visu_pars`  ##$VisuCoreOrientation=( 1, 9 )
1 0 0 0 0 -1 0 1 0
- [ ] `vc_position` comes from `visu_pars` ##$VisuCorePosition=( 1, 3 )
-6.1 -7 7.9
- [ ] `subject_position` comes from `subject` ##$SUBJECT_position=SUBJ_POS_Supine
- [ ] `voxel_sizes` comes from `method` ##$PVM_SpatResol=( 3 )
0.1 0.1 0.1

**Comment by saskiad** [comment]
I've looked at these mostly for a scan that *is* a primary scan, and it's possible that for the setup scans some of the values we get for these will be wonky, so I would recommend looking at what you get back for the different variables.

**Comment by jtyoung84** [comment]
This was moved to a different repository
