### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by galenlynch** [AllenNeuralDynamics/aind-data-transfer#244]
Apologies if this already exists in some form, I couldn't find it if it does. 

As this project has evolved, the way users interact with it has changed over time. As a user, the easiest way to keep on top of these changes and figure out how to use it at any given time is to talk to @jtyoung84 or ask other users what's changed recently. If instead there was a [changelog](https://keepachangelog.com/en/1.0.0/), users could figure out what's changed and how to use the project without digging through git commits.

**Comment by dyf** [comment]
@galenlynch Thanks, good idea.  FYI we are migrating this to a webservice that is always up-to-date, so that you don't have to worry about it.

**Comment by jtyoung84** [comment]
# User story
As a user, I want a change log available, so I can easily see what changed across versions.

# Acceptance criteria
- [ ] Given a pull request is merged into main, then a github action will run which will automatically update a CHANGELOG.md file using the commit messages
- [ ] A developer should be able to update the CHANGELOG manually if needed

# Sprint Ready Checklist 
- [ ] 1. Acceptance criteria defined
- [ ] 2. Team understands acceptance criteria
- [ ] 3. Team has defined solution / steps to satisfy acceptance criteria
- [ ] 4. Acceptance criteria is verifiable / testable
- [ ] 5. External / 3rd Party dependencies identified
- [ ] 6. Ticket is prioritized and sized

# Notes
*Add any helpful notes here.*

**Comment by jtyoung84** [comment]
We're probably going to sunset this repo soon
