### ISSUE TITLE
Github version tags are applied before version bump

### ISSUE THREAD

**Issue by kgabor** [AllenNeuralDynamics/aind-data-transfer#268]
The version tags on the github repo refer to the commits before the version number is bumped in the code.
Eg. checking out and installing tag `v0.25.1` will self-report as `v0.25.0`. I guess this is a confusion between the conventions that a development version already refers to the would be released version number and the one that refers to the last released version.

```
git checkout v0.25.1
pip install -e .

...
Successfully installed aind-data-transfer-0.25.0
```

Note: `pip install aind-data-trasfer==0.25.1` seems to install the correct version.

**Comment by jtyoung84** [comment]
Will be closed by https://github.com/AllenNeuralDynamics/aind-github-actions/pull/12

**Comment by jtyoung84** [comment]
Moving forward, fixed by: https://github.com/AllenNeuralDynamics/aind-github-actions/pull/12
We probably won't adjust the old tags though.
