### ISSUE TITLE
experiment_type input parameter `SPOPHYS` is expecting a full string, instead of enum header

### ISSUE THREAD

**Issue by Sun-flow** [AllenNeuralDynamics/aind-data-transfer#269]
User reports error attempting to input data using the following command:
![image](https://github.com/AllenNeuralDynamics/aind-data-transfer/assets/18150105/84713ed5-6ef8-46fb-be65-b27444103528)

Error was resolved when changing the experiment_type filed to `single-plane-ophys`, which is not a listed header in our readme (expected header would be SPOPHYS)

**Comment by jtyoung84** [comment]
We can update the readme file to make it clear the exp_type param should be set using the modality abbreviation
