### ISSUE TITLE
Missing dependencies in pip installation

### ISSUE THREAD

**Issue by kgabor** [AllenNeuralDynamics/aind-data-transfer#274]
Pip installation does not pull all the necessary dependencies for the `transformations.ome_zarr` module, even in the `[full]` installation.

To reproduce, in a fresh pip installation, import `aind_data_transfer.transformations.ome_zarr`.

It seems that the addition of the following ones resolves the issue though I have not checked very thoroughly for implicit dependencies (eg. h5py is pulled in by hdf5plugin): `tifffile`, `ome-zarr`,  `xarray-multiscale`, `hdf5plugin`, `kerchunk`.

**Comment by jtyoung84** [comment]
These dependencies are added via the postInstall script in the root directory
