### ISSUE TITLE
use abbreviations for modalities

### ISSUE THREAD

**Issue by dyf** [AllenNeuralDynamics/aind-data-transfer#282]
On the excel input sheet and in the generated directory names, use `Modality.abbreviation` rather than the enum name.

**Comment by jtyoung84** [comment]
@dyf One of the hesitations I had doing this initially was that there is no guarantee abbreviations are expected to be unique. I can make this change, but please bear this in mind.

**Comment by dyf** [comment]
@jtyoung84 understood. we can had some validation to the schema to prevent this.

**Comment by mekhlakapoor** [comment]
> @jtyoung84 understood. we can had some validation to the schema to prevent this.

we added a check for this in this `[ aind-data-schema PR](https://github.com/AllenNeuralDynamics/aind-data-schema/pull/491)` . if there are duplicates, it will fail the unit test
