### ISSUE TITLE
Make ephys compression more reproducible 

### ISSUE THREAD

**Issue by bjhardcastle** [AllenNeuralDynamics/aind-data-transfer#321]
Part of the processing that happens before upload involves taking a median of a random subset of data. The function in SpikeInterface that does this can accept a seed for an rng:

https://github.com/SpikeInterface/spikeinterface/blob/main/src/spikeinterface/preprocessing/correct_lsb.py

But it isn't being used at the moment:
https://github.com/AllenNeuralDynamics/aind-data-transfer/blob/main/src/aind_data_transfer/transformations/ephys_compressors.py#L177

This makes it impossible to verify that uploaded data are identical to the original raw data.

**Comment by jtyoung84** [comment]
Closed by https://github.com/AllenNeuralDynamics/aind-data-transfer/pull/322
