### ISSUE TITLE
Deprecation warning when running ephys reader

### ISSUE THREAD

**Issue by jtyoung84** [AllenNeuralDynamics/aind-data-transfer#40]
**Describe the bug**
A lot of warnings show up when running the ephys upload job.
```
warnings.warn(
/miniconda3/envs/nd-data-transfer/lib/python3.8/site-packages/packaging/version.py:111: DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major release
```

**To Reproduce**
1. Run the test_read unit test
2. See warning shows up

**Expected behavior**
There shouldn't be any warnings if we can avoid it

**Additional context**

**Comment by alejoe91** [comment]
@jtyoung84 I have tried to track down where this is triggered, with no luck!

It's probably some dependency, because in SpikeInterface we don't have any `LegacyVersion`

**Comment by jtyoung84** [comment]
Haven't seen the warnings in a while...
