### ISSUE TITLE
Ephys team can run ephys transfer job themselves

### ISSUE THREAD

**Issue by dyf** [AllenNeuralDynamics/aind-data-transfer#52]
Originally this issue was about automating file reorganization.  I've updated it to be about simply making sure that the ephys team can run this job themselves.

Acceptance Criteria:

- [x] ephys team can run transfer job themselves
- [x] ephys team can find their data in codeocean
- [x] ephys team can find their results in codeocean

old version below:

Right now the ephys team is manually reorganizing files from different hard drives.  

- [x] Confirm with team (anna) about what they are doing
- [x] Update the ephys job step that is reorganizing videos and such to automate this

**Comment by jtyoung84** [comment]
Waiting for ephys team to generate new data sets

**Comment by jtyoung84** [comment]
Installed and ran the aind-data-transfer scripts on an ephys workstation
