### ISSUE TITLE
write_ome_zarr.py: incorrect behavior with --resume flag

### ISSUE THREAD

**Issue by carshadi** [AllenNeuralDynamics/aind-data-transfer#78]
**Describe the bug**
Currently, calling `write_ome_zarr.py` with the `--resume` flag will perform the following check to see if a tile
has already been written

https://github.com/AllenNeuralDynamics/aind-data-transfer/blob/720a57c20c79d4b5cce1ce51dfe8dd9b750115ee/src/aind_data_transfer/transcode/ome_zarr.py#L260-L267

This was meant as a placeholder, and is incorrect for a couple reasons. 1) since it only takes into account the shape of the array, not stored data. 2) it only checks the lowest resolution level, since at the time they were written in order from high -> low. All levels are written simultaneously now.

To actually resume in case of failure, what I've been doing is checking the logs to see the tile that was currently being written, then delete that (partially written) tile from the output location, and finally restart the job using the `--resume` flag, which skips over all the existing arrays (whether or not they were fully written) in the output store. 

This issue https://github.com/zarr-developers/zarr-python/issues/587 describes a few different ways to detect missing chunks in a Zarr array. The one that seemed most promising to me was taking the ratio of [nchunks_initialized](https://github.com/zarr-developers/zarr-python/blob/be29d3659daf83b8ff2b119ac98d97c47324706c/zarr/core.py#L380) and [nchunks](https://github.com/zarr-developers/zarr-python/blob/be29d3659daf83b8ff2b119ac98d97c47324706c/zarr/core.py#L374) , which should be `1` if all chunks were written (assuming there are no empty "zero" chunks). The methods which scan the entire array and/or compute checksums feel less appealing to me since it _might_ end up being faster to just re-write the tile, but could be worth investigating depending on how thorough we want to be.

**Comment by jtyoung84** [comment]
@mekhlakapoor Follow up to see if this is still an issue

**Comment by mekhlakapoor** [comment]
This is still an issue, but not for the original reasons. Cameron's updated the ticket, but it's not currently in progress.

**Comment by carshadi** [comment]
Closing as this is no longer relevant with the refactoring of the zarr upload job.
