### ISSUE TITLE
Ephys job uses codeocean trigger capsule

### ISSUE THREAD

**Issue by dyf** [AllenNeuralDynamics/aind-data-transfer#81]
Acceptance Criteria:
- [x] The last step of the ephys upload job triggers a codeocean job triggering capsule with the spike sorting capsule ID
- [ ] The job triggering capsule registers a data asset, triggers the desired capsule, registers the run output as a data asset
- [ ] raw and result data assets are named according to `aind-data-schema` conventions (see: `RawDataAsset` and `DerivedDataAsset`).

**Comment by jtyoung84** [comment]
We're still sorting out how to automatically capture and register a result

**Comment by dyf** [comment]
> We're still sorting out how to automatically capture and register a result

There is an API for this: 

```
curl -H "Content-Type: application/json" -u USER_API_TOKEN: -X POST https://codeocean.com/api/v1/data_assets --data-raw '{
   "name": "Data asset From API",
   "description": "An example for creating data asset from CO API",
   "mount": "some-folder",
   "tags": [ "keyword1", "keyword2" ],
   "source": {
   "computation": {
     "id": "some-computation-id"
     }
   }
}
```

Where `some-computation-id` is the is of the Run.
